version: "3"

services:
  cactusshort:
    depends_on:
      - db
    env_file: ".env"
    build:
      context: .
    volumes:
      - ./logs:/var/logs
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: cactustech
