version: "3"

services:
  app:
    depends_on:
      - db
    env_file: ".env"
    networks:
      - url_shortener
    build:
      context: .
    ports:
      - "9000:9000"
    volumes:
      - ./logs:/var/logs
  db:
    image: mongo
    restart: always
    networks:
      - url_shortener
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: cactustech
networks:
  url_shortener:
