version: "3"

services:
  cactusshort:
    depends_on:
      - db
    env_file: ".env"
    build:
      context: .
    volumes:
      - ./logs:/var/logs
    networks:
      - app_network
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: cactustech
    networks:
      - app_network
networks:
  app_network:
    name: ${DOCKER_NETWORK}
    external: ${DOCKER_IS_EXTERNAL_NETWORK}
